//	Header generated by Constructor for Palm OS¨ 1.5
//
//	Generated at 3:47:49 PM on Thursday, May 02, 2002
//
//	Generated for file: C:\Program Files\Metrowerks\CodeWarrior for Palm OS Platform 7.0\Other SDKs\Handspring\HubScan\Rsc\HubScan.rsrc
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE FROM CONSTRUCTOR FOR PALM OS¨;
//	- DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Palm App Name: 		"HubScan"
//
//	Palm App Version: 		"1.0"



//	Resource: tFRM 1000
#define MainForm                                  1000	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 0, Save Behind = 0, Help ID = 0, Menu Bar ID = 1000, Default Button ID = 0)


//	Resource: tFRM 1100
#define AboutForm                                 1100	//(Left Origin = 2, Top Origin = 2, Width = 156, Height = 156, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define AboutOKButton                             1105	//(Left Origin = 58, Top Origin = 133, Width = 40, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define AboutTitleLabel                           1102	//(Left Origin = 40, Top Origin = 27, Usable = 1, Font = Large)
#define AboutText1Label                           1103	//(Left Origin = 37, Top Origin = 76, Usable = 1, Font = Standard)


//	Resource: tFRM 1300
#define SortForm                                  1300	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 0, Save Behind = 0, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define SortCancelButton                          1302	//(Left Origin = 43, Top Origin = 143, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define SortSelectButton                          1303	//(Left Origin = 91, Top Origin = 143, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define SortNamesList                             1301	//(Left Origin = 36, Top Origin = 22, Width = 100, Usable = 1, Font = Standard, Visible Items = 9)


//	Resource: Talt 1001
#define RomIncompatibleAlert                      1001
#define RomIncompatibleOK                         0

//	Resource: MBAR 1000
#define MainFormMenuBar                           1000

//	Resource: MENU 1000
#define MainOptionsMenu                           1000
#define MainOptionsSelectSortPlan                 1000
#define MainOptionsScanPackage                    1001
#define MainOptionsAboutHubScan                   1002
